name: Node.js Package Publish

on:
  release:
    types: [created]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          yarn set version berry
          yarn install --immutable
          yarn test

  publish-npm:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: yarn set version berry
      - run: yarn config set npmRegistryServer https://registry.npmjs.org
      - run: yarn config set npmAuthToken $NPM_TOKEN
      - run: yarn npm publish
