name: Node.js Package Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          yarn set version berry
          yarn install --immutable
          yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: |
          yarn config set npmAuthToken $NODE_AUTH_TOKEN
          yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
